### ISSUE TITLE
PHP Error still reports success

### ISSUE THREAD

**Issue by matdave** [appleboy/ssh-action#151]
I'm not sure if this is a bug or something I am missing, but when my command runs into an issue it still reports successful. 

E.g. 

```php
======CMD======
rm -rf /www/cache/yext/
php /www/script/yextdeploy.php
======END======
err: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to xxxx\Api\Yext\Deploy::publishObject() must be of the type bool, array given, called in /www/xxxx/src/Yext/Deploy.php on line 43 and defined in /www/xxxx/src/Yext/Deploy.php:72
err: Stack trace:
err: #0 /www/xxxx/src/Yext/Deploy.php(43): xxxx\Api\Yext\Deploy->publishObject('xxxx\\Model\\L...', Array)
err: #1 /www/script/yextdeploy.php(14): xxxx\Api\Yext\Deploy->execute()
err: #2 {main}
err:   thrown in /www/xxxx/src/Yext/Deploy.php on line 72
==============================================
✅ Successfully executed commands to all host.
==============================================
```

Is there a way to get it to not show successful if there was an error reported by the action?

**Comment by matdave** [comment]
This was a derp. I found I was missing `script_stop` on this action config
